### ISSUE TITLE
Alias mdlUpgrade directive as mdl

### ISSUE THREAD

**Issue by bisubus** [sabbirrahman/ng2-mdl#1]
Can we alias `mdlUpgrade` directive selector as `mdl`?

It seems to be semantically correct decision to me, and it looks like [I'm not the only one](http://stackoverflow.com/a/35451821/3731501). `upgrade` suffix is just redundant here and makes the layout less expressive (if this is even possible, considering the verbosity of MDL).

By the way, have you got any road map/task list? I intend to stick to this Material implementation for some projects and would happily collaborate on the repo.

**Comment by sabbirrahman** [comment]
Sure. I'll create the alias by tonight. I've planed to upgrade this package to support @angular2.0.0-rc.3 which have introduced new @angular/forms module. It will be great to have a collaborator. :+1:
