### ISSUE TITLE
Can't compile in vscode and angular2 rc6 Quickstart

### ISSUE THREAD

**Issue by mickmuln** [sabbirrahman/ng2-mdl#13]
Hi,  I am trying to run in the angular2 rc6 quickstart from vscode but I am getting the following typescript compiler errors 

node_modules/ng2-mdl/src/mdl-check-box.component.ts(44,10): error TS7006: Parameter 'checked' implicitly has an 'any' type.
node_modules/ng2-mdl/src/mdl-check-box.component.ts(51,15): error TS7006: Parameter '_' implicitly has an 'any' type.
node_modules/ng2-mdl/src/mdl-radio.component.ts(46,10): error TS7006: Parameter 'value' implicitly has an 'any' type.
node_modules/ng2-mdl/src/mdl-radio.component.ts(53,15): error TS7006: Parameter '_' implicitly has an 'any' type.
node_modules/ng2-mdl/src/mdl-select.component.ts(54,10): error TS7006: Parameter 'value' implicitly has an 'any' type.
node_modules/ng2-mdl/src/mdl-select.component.ts(79,15): error TS7006: Parameter '_' implicitly has an 'any' type.
node_modules/ng2-mdl/src/mdl-switch.component.ts(43,10): error TS7006: Parameter 'checked' implicitly has an 'any' type.
node_modules/ng2-mdl/src/mdl-switch.component.ts(50,15): error TS7006: Parameter '_' implicitly has an 'any' type.
node_modules/ng2-mdl/src/mdl-text-field.component.ts(48,10): error TS7006: Parameter 'value' implicitly has an 'any' type.
node_modules/ng2-mdl/src/mdl-text-field.component.ts(55,15): error TS7006: Parameter '_' implicitly has an 'any' type.

I have typescript ^2.0.0 installed, any thoughts?

**Comment by mickmuln** [comment]
I have fixed the issues in the source,

**Comment by sabbirrahman** [comment]
Upgrading to version 1.0.0 should solve it.
