### ISSUE TITLE
ReferenceError: componentHandler is not defined

### ISSUE THREAD

**Issue by NiKoLai1983** [sabbirrahman/ng2-mdl#14]
Hi sabbirrahman,

I'm having issues trying to insert a simple ng2-mdl component and I don't know if I'm missing steps or there is something wrong in the code:

With nodejs v6.5.0 and npm 3.10.3:
- I created a new Angular 2.0.0.rc6 project following the angular quickstart guide (https://angular.io/docs/ts/latest/quickstart.html)
- `npm install`
- `npm install --save ng2-mdl`
- I do the following modifications to systemjs.config.js:

```
map: {
      .....
      'ng2-mdl': 'npm:ng2-mdl',
      .....
}

packages: {
      .......
      'ng2-mdl': {
          main: './index.js'
      },
      .......
}
```

Otherwise, when loading the app, I get the following error:

`Error: XHR error (404 Not Found) loading http://localhost:3000/ng2-mdl(…)`
- `npm start`
- When loading the page, the browser apparently gets correctly the files, but fails loading:

```
ReferenceError: componentHandler is not defined
    at MdlDirective.ngOnInit (mdl.directive.ts:10)
    at DebugAppView._View_MdlTextFieldComponent0.detectChangesInternal (MdlTextFieldComponent.ngfactory.js:90)
    at DebugAppView.AppView.detectChanges (core.umd.js:12061)
    at DebugAppView.detectChanges (core.umd.js:12166)
    at DebugAppView.AppView.detectViewChildrenChanges (core.umd.js:12087)
    at DebugAppView._View_AppComponent0.detectChangesInternal (AppComponent.ngfactory.js:116)
    at DebugAppView.AppView.detectChanges (core.umd.js:12061)
    at DebugAppView.detectChanges (core.umd.js:12166)
    at DebugAppView.AppView.detectViewChildrenChanges (core.umd.js:12087)
    at DebugAppView.AppView.detectChangesInternal (core.umd.js:12072)
```

I've also tried the angular2-webpack-starter with equal results.

Thanks in advance for your help,

JPV

**Comment by sabbirrahman** [comment]
The library is actually a wrapper for [Material Design Lite](http://www.getmdl.io/), which means you'll have to install and include the .js and .css files of material design lite too. Here is how you can do it in angular2-webpack-starter.

Step 1: Install
`npm install --save material-design-lite`
`npm install --save mdl-select-component // for select input (optional)`

Step 2: Include JavaScript Files
Require the material-design-lite and mdl-select-component's .js files in your root component.

```
import { Component, ViewEncapsulation } from '@angular/core';
require('material-design-lite/dist/material');
require('mdl-select-component/mdl-selectfield.min'); // for select input (optional)
```

Step 3: Include CSS Files
Add the .css files in your root component decorator's styles attribute:

```
@Component({
    selector: 'app',
    encapsulation: ViewEncapsulation.None,
    styles: [
        require('material-design-lite/dist/material.min.css'),
        require('mdl-select-component/mdl-selectfield.min.css') // for select input (optional)
    ]
})
```

I hope you can figure a way to do this for angular-cli as well.

Note: If you don't need to use select input you don't have to install and require mdl-select-component's .js and .css files.

**Comment by NiKoLai1983** [comment]
Thanks! Works like a charm!
