### ISSUE TITLE
ng2-mdl and angular-cli (webpack version)

### ISSUE THREAD

**Issue by bonnici** [sabbirrahman/ng2-mdl#15]
I am trying to use ng2-mdl in the new webpack version of [angular-cli](https://github.com/angular/angular-cli), but I'm running into some issues. When I import and then try to add the Ng2MdlModule to my module's imports, I get the error `Uncaught Error: Unexpected value 'Ng2MdlModule' imported by the module 'AppModule'`. I saw issue #3 but since they changed from SystemJS to webpack, I don't think it's necessary to do anything special to get the app to find the .js files and as far as I know you should just need to run `npm install --save ng2-mdl` and it should be available for import. Any help or advice would be appreciated.

**Comment by bonnici** [comment]
I've getting the same error with 2 other webpack seeds ([angular2-webpack-starter](https://github.com/AngularClass/angular2-webpack-starter) and [angular2-webpack](https://github.com/preboot/angular2-webpack)) so it might be a general issue with the latest angular or webpack versions. I'm using:
- node v6.5.0
- npm v3.10.6
- angular v2.0.0
- webpack v2.1.0-beta.22 (angular-cli & angular2-webpack-starter)
- webpack v1.13.2 (angular2-webpack)

**Comment by bonnici** [comment]
Now I'm pretty sure this is just related some change in metadata generation between RC6 and release. I just copied all the .ts files to a local folder (ng2-mdl.module.ts, mdl-button.component.ts, etc) and imported that instead of the npm version (`import { Ng2MdlModule } from '../ng2-mdl/ng2-mdl.module';`) and everything seems to be working fine.

**Comment by sabbirrahman** [comment]
Upgrading to version 1.0.0 should solve it.

**Comment by bonnici** [comment]
Thanks - but something strange is still happening. It seems to work but I need to use `import { Ng2MdlModule } from 'ng2-mdl/src/ng2-mdl.module';` rather than just `import { Ng2MdlModule } from 'ng2-mdl';`. It might be because of the workaround I was using before so I'll see if I can do some testing later.

**Comment by bonnici** [comment]
Yeah same issue with a brand new angular-cli app. It looks importing from `ng2-mdl/ng2-mdl` and `ng2-mdl/universal` works, but not from just plain `ng2-mdl`.

**Comment by mischelebuha** [comment]
I created a new project with the latest angular-cli.
I have the same error:

> Error: Unexpected value 'Ng2MdlModule' imported by the module 'AppModule

angular-cli: 1.0.0-beta.16
node: 6.7.0
npm v3.10.6
angular v2.0.0

I used:

ng2-mdl
ng2-mdl/ng2-mdl
ng2-mdl/src/ng2-mdl.module

The same error.

**Comment by kmcgeown** [comment]
Migrating from Ang 2.0.0.RC5 to 2.1.0 and having the same Error. Tried all the above but no joy.

**Comment by sabbirrahman** [comment]
Which version of ng2-mdl are you using? Just installed ng2-mdl v1.0.3 with angular-cli. Working fine for me. I'm using angular-cli: 1.0.0-beta.18 & angular v2.1.0
