### ISSUE TITLE
Select value does not update until manually changing value

### ISSUE THREAD

**Issue by qdouble** [sabbirrahman/ng2-mdl#8]
I've noticed when using select, that the value does not update to the correct value until you manually update it... so if you get response from the server for example, it will just show the first slot even if a different value was selected. Any ideas on how to fix/update this properly?

**Comment by sabbirrahman** [comment]
I've just fixed the bug in version 0.6.8. Please update the package and check the [Documentation](http://sabbirrahman.github.io/ng2-mdl/#/mdl-select).

**Comment by qdouble** [comment]
@sabbirrahman thanks a lot for the quick update... there's a typo in your new example in the docs `binding: sting = 'value3';` should be `string`

As an off topic comment, I've been playing with mdl/ng2 all day and it seems like using mdl components in Angular 2 is brittle... the direct dom access of componentHandler make it unusable if you plan on using Universal/Web Workers.. and there is also flakiness with buggy loading of some elements depending on how you arrive upon them. Good library though, not a knock on you, just hoping a more native ng2 solution comes along until the official material 2 library is full featured.

**Comment by sabbirrahman** [comment]
Thanks for your comment. I'm trying to make it Universal/Web-Worker friendly. I hope I'll be able to update it soon.
